### ISSUE TITLE
Consider a lower timeout in sleep mode

### ISSUE THREAD

**Issue by phillco** [knausj85/knausj_talon#1103]
This came up in today's Cursorless meetup. One common user problem we've noticed people having is having a dedicated wake command in sleep mode, but having it (probably incorrectly) anchored on both ends to avoid false positives, like:

`^talon wake$: ...`

The problem is that then they get stuck in a loop, where they keep trying to say the wake phrase, but because they haven't hit the speech timeout, their anchored command is never recognized, and Talon never wakes.

Naturally the right solution is probably get rid of the preceding anchor, but @pokey had the simple suggestion of _lowering_ the timeout in sleep mode (100ms). That would help people who do get caught with the this "inescapable loop" problem a little bit.

I can't think of a reason not to have a lower timeout in sleep mode -- can others?

**Comment by rntz** [comment]
It feels a bit weird that sleep mode should have a different timeout, might screw up some people's timing (eg. if they just speak slowly). But I guess if it's already screwing up people's timing maybe we should do it. I would like to hear @lunixbochs opinion on this since he raised the default timeout to 300ms and we're proposing changing that within sleep mode.

**Comment by pokey** [comment]
One concern with this approach is that it almost feels like we're trying to functionally un-anchor the command by lowering the speech timeout

**Comment by lunixbochs** [comment]
Maybe do this?
```
^(talon wake)+
```

Please don't change the timeout in community repos.
