### ISSUE TITLE
toggle display instead of show + hide display

### ISSUE THREAD

**Issue by ym-han** [knausj85/knausj_talon#138]
May i make a quick suggestion about a design choice I've seen in the repo? I've noticed that whenever we need to show/hide some gui, the interface has tended to use two commands, e.g. `show formatters` and `hide formatters`. May i suggest that we try to use just one command instead, e.g., `toggle formatters` (or formatter display etc)? 

The main reason is that the fewer the number of voice commands one has to remember, the better. But this may just be a purely stylistic preference.

**Comment by fidgetingbits** [comment]
Where we have the possibility to query the current state, I agree it's nice to use `toggle`. However, for most external apps where we can't query the state but still want to toggle settings, we'll be forced to use `show`/`hide`. So this leads to a bit of desync of commands, unless for talon stuff we supported both `show`/`hide` and `toggle`. If some places you have to say `toggle`, and others `show`/`hide`, I suspect some users will find it even more confusing than forcing `show`/`hide` everywhere.

I'd be happy having both available though.

**Comment by ym-han** [comment]
Yeah i ran into this actually after refactoring a few show/hide to toggles...

My solution was to bind only toggle for the user, but still let scripts use the show / hide methods if necessary. This seems to work ok in practice, but there may be areas where it won't work well; I haven't spent enough time playing with these things to know.

**Comment by ym-han** [comment]
I see; hadn't thought about external apps...

**Comment by fidgetingbits** [comment]
I suspect there will be, but not sure on frequency. The most obvious one that comes to mind would be vim, which in theory we can query the current setting, but you have to actually implement support in python. but as an example right now in vim if I do a search it automatically highlights the results of the words, so I have effectively a `show` and `hide` highlight command. But at the moment because I haven't been able to use the RPC functionality yet, I wouldn't be able to do something like `toggle`.  So above comment is mostly contextualized around having consistency of commands when encountering situations like that.

In general for each app you need to have a way to interface with it to actually know and a lot of people are going to write more simple grammars in talon files that just trigger the command to set/ unset or show/hide the setting. 

But ya, I think the best solution is just a support both when possible

**Comment by knausj85** [comment]
Yeah, toggling via a single, shorter command is generally better where possible. I mostly followed the conventions of the old api starter pack from the outset, which typically used show/hide (or otherwise separate commands) as I recall.

Another example for fidget’s thing would be eg browser history. Until we have a plugin like dragon or something, show/hide history is our best bet.

**Comment by knausj85** [comment]
Fwiwi, I do hesitate to support both in any single app, at least in my depot, just so the grammar is kept small.

**Comment by knausj85** [comment]
I've moved everything I can to this approach. I chose not to use toggle here since I personally find "toggle" tiresome.

```
running list: user.switcher_toggle_running()
format help: user.formatters_help_toggle()
format recent: user.formatters_recent_toggle()
command history: user.history_toggle()
``
