### ISSUE TITLE
Can we watch the VSCode snippet directories and dynamically update the snippets?

### ISSUE THREAD

**Issue by knausj85** [knausj85/knausj_talon#168]
Good idea or bad idea?

https://github.com/knausj85/knausj_talon/commit/1e4eea598e795c77da960da4e0880baddd4fa2f7

**Comment by fidgetingbits** [comment]
I like this idea, I think someone on slack recently said they have code for auto generating rules based on snippets so it seems like it could work, but I forget who. certainly easier then updating the list ourselves each time (or what I did for as for vim snippets phrase which was a manual rule for each thing),  especially as everyone might have different versions of snippets

**Comment by knausj85** [comment]
The biggest problem is perhaps the naming convention (or lack thereof) of clips is total garbage.

Kinda leaning towards something like this:
- Watcher (re)generates a (per language or whatever) CSV file: friendly name, actual snippet name. Any known clips are of course preserved, allows manual edit of the friendly name.

**Comment by knausj85** [comment]
@fidgetingbits 
If you got time, take a peek at the first pass. I could use an extra brain!
https://github.com/knausj85/knausj_talon/commits/snippet-watcher

- Initial support for VSCode's JSON snippets. I have no idea what vim does.
- Requires jsoncomment, which you can pip install via ~\.talon\.venv\Scripts\pip.bat
- if you modify snippet_watcher.py, it won't force a reload of e.g. python_snippets.py, have to modify that too at the moment. May be a talon bug.

For user-defined snippets, I think this works well since we can give them dictation-friendly names.  For packages, we might be better off with hardcoded things...

**Comment by fidgetingbits** [comment]
I am back after a week away so I'll try to find time this week to take a look

**Comment by knausj85** [comment]
@brxck - you might be interested in taking a peek at this too
https://github.com/knausj85/knausj_talon/commits/snippet-watcher

**Comment by knausj85** [comment]
For a bit more detail on my current thinking, I'm considering replacing some things in programming.talon with snippets.

e.g., for vscode defining snippets like below, and using the "prefix" for friendly-ish dictation. 

```
{
	"private function": {
		"prefix": "funky",
		"body": [
			"private ${1:void} ${2:functionName}($3)",
			"{",
			"\t$4",
			"}",
		],
		"description": "private function"
	},
	"protected function": {
		"prefix": "pro funky",
		"body": [
			"protected ${1:void} ${2:FunctionName}($3)",
			"{",
			"\t$4",
			"}",
		],
		"description": "protected function"
	},

        ...
```
might replace

```
^funky <user.text>$:
    ...
```
in programming.talon.

I don't know how this would carry over to e.g. vim or jetbrains, but conceivably we could build a library of dictation-friendly user snippets as-needed over time.

**Comment by fidgetingbits** [comment]
as for replacing from `programming.talon` I almost things like this should be something that a setting dictates? just in so far as you don't want people using talon to require to be used specific editors or snippets? but if you have the snippets or editor then you can gain the extra benefit? maybe it's too much duplication though..

it seems like a really good idea specifically because it uses json for the snippets in vscode, so it's a bit easier to inject your own dict entry.

the vim snippets depend on the actual snippet plug-in that you use (which I imagine there are  few), but the one I use doesn't use something like json for tracking the snippets unfortunately. so adding in something like your own dictionary tag that talon could find doesn't seem too feasible. one example for C, which is in a file just called `c.snippets` would be:

```
snippet main "main() (main)"
int main(int argc, char *argv[])
{
	${VISUAL}$0
	return 0;
}
endsnippet
```

I guess for something like what I use in vim (ultisnips) we could have our own talon json file or just use the python lists. watching this snippet file for changes won't help probably though, since it needs that correlation in a list somewhere. I suppose doing it in our json file would make it a bit easier for people that aren't python coders to update their snippet support? but at least otherwise for the vim stuff the way I use it I don't see that watching the file will help unfortunately. I certainly might not be thinking of some useful scenario though..

one other random thing that I do in vim with snippet is press the tab key when the snippet is actually entered so that it auto expands right awy, because by default just adding the text doesn't quite trigger it. I guess you don't have to do that for vscode?

**Comment by knausj85** [comment]
That’s too bad re vim, though I suppose its snippet support probably largely predates json haha. With a convention of some sort, this really goes a long way imo. 

I figured replacing programming.talon stuff was a long shot. I think there’s room for both things anyway, though I question some stuff in programming.talon for typed languages in particular.

Yeah, once you select the snippet in vscode and hit enter, it’s fully expanded.

Thanks for poking at this.
