### ISSUE TITLE
rationalize word_selection.{py,talon}

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#236]
I'm not sure what word_selection.py is supposed to be doing.

- Its actions are not clearly documented: How are they different from edit.word_right/left and edit.extend_word_right? Why are there three variants, normal/small/big? What does each of them do differently than the rest? – this should all be in their doc strings.

- It doesn't work consistently (at least for me). In particular, `word prev` doesn't work in gedit if the cursor is at the end of the last line in a file with no new line at the end, and none of the commands work at all in emacs. This is especially important since it adds global-context commands.

- The code is complex and uncommented, which makes it hard to figure out what's going on or fix what's broken on linux.

@dwiel could you clarify?

**Comment by dwiel** [comment]
sure thing, I will explain here, and then if it is clear make a pull request.

`word prev <number>` selects the number'th word before the cursor. For example: `hello world foobar|` `word prev 2` selects the word `world`. This is different than `extend_word_left` because in this case only `world` is highlighted and not `world foobar`.

normal|small|big specifies which characters qualify as a word. For example: `self.function(argument)|` `word prev 1` selects the word `argument` and not the `)`.

`small` indicates that `_` does not qualify as a word. For example: `self.function(long_argument_name)|` `word prev 3` selects the word `long` since each part of `long_argument_name` qualifies as a different "word".

**Comment by dwiel** [comment]
as for working on linux, it looks like there is a general bug that was introduced when I refactored the clip code, not specific to liunux. I'll check that out as well.

**Comment by knausj85** [comment]
Semi-related. These commands are very useful. I wonder if they should be available in dictation mode.

**Comment by knausj85** [comment]
I don't believe this is relevant with the new navigation command stuff
