### ISSUE TITLE
Firefox windows tab next does not cycle through all tabs?

### ISSUE THREAD

**Issue by rntz** [knausj85/knausj_talon#331]
I don't have windows so I can't verify this but in the talon zoom today tararoys showed that tab next/last in firefox did not work for her, in the following sense: repeated `tab next` only switched between the most recent two tabs, instead of cycling between all tabs. This appears to be because windows expects you to hold down the control key when using control tab. Apparently this can be fixed by using control+pageup/pagedown instead.

**Comment by rntz** [comment]
It looks like control-pageup/pagedown also work on linux, so maybe those should just be the defaults.

**Comment by ShuPink** [comment]
Hiya, just out of interest, I use Firefox on Windows and "tab next" / "tab last" works as expected for me (cycles through all tabs, not back and forth).
It's currently assigned to ctrl-tab.

**Comment by knausj85** [comment]
Looks like firefox has a cute little switcher mapped to ctrl-tab by default now, which can be disabled to revert to the previous keys. "fun"
https://support.mozilla.org/en-US/kb/tab-preferences-and-settings

Since this is allegedly the default for firefox, I've switched it over
https://github.com/knausj85/knausj_talon/commit/3cc62c09b4eaba099d396f5d63ab5d2d568353df
