### ISSUE TITLE
Order of words in homophones.csv is not respected

### ISSUE THREAD

**Issue by seabadger** [knausj85/knausj_talon#411]
For example: regardless of whether homophones.csv has "bytes,bites" or "bites,bytes", dictation (using 'word', 'sentence', 'say', etc) always chooses "bites".
My understanding is that the first word listed is supposed to be preferred.

**Comment by knausj85** [comment]
Hmm, homophones has never been involved in word/sentence/etc. It's just for changing the word as-needed later. 

I'd be a little hesitant to change this since a better language model will likely do better in the future, at least for e.g. say.

**Comment by pokey** [comment]
So for “say” I agree I’d be super hesitant to override the language model.
I do wonder tho for things like “camel”, where I would imagine the language
model might not be as helpful? I wonder if it would make sense to have some
formatters that respect homophone ordering

**Comment by splondike** [comment]
I think we should wait for an officially supported API for expressing word preferences before doing something like this. aegis has traditionally preferred the approach of improving the speech recognition engine across the board rather than allowing these sorts of customizations. Closing for the moment.
