### ISSUE TITLE
Inconsistent command structures

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#459]
Sometimes the commands are structured `verb noun` and sometimes `noun verb`.

An example is `bookmark show` vs `show extensions`. I think that if these were consistent, it would be much easier to learn the community talon commands.

I'm looking at `knausj_talon/apps/generic_browser.talon` in this case, though the issue likely is more widespread. 

Cheers,
Xavier

**Comment by brxck** [comment]
From the README:

> commands are subject to change. We do our best to minimize changes, but we are moving to an [object][verb] standard slowly but surely.

And prior discussion is in https://github.com/knausj85/knausj_talon/issues/148

**Comment by xavier630** [comment]
Awesome, thanks for that, apologies for re-addressing.

In terms of this specific file, are you okay with me fixing the commands in `generic_browser.talon`?

**Comment by brxck** [comment]
No worries, I just saw this pop up in Slack and thought I'd share what I knew!

I'm not actually one of the maintainers here, so I'll leave that to them. Appreciate your interest in improving the community repo!

**Comment by splondike** [comment]
In terms of making things consistent I think we can really only do this in an additive way in order to maintain backwards compatibility with what existing users are expecting. That is, I'd be happy if you to add more voice commands as long as we keep the existing ones in there.

In the longer term I believe the plan is to move away from the monorepo type approach exemplified by knausj_talon towards having a bunch of individual plugins which can be easily managed by a first party user interface. The point when we have that interface seems like a good time to significantly revisit the naming scheme for voice commands as a community.

**Comment by splondike** [comment]
Browser issue has been addressed by xavier I think. Closing the ticket as other cased would be dealt with case by case.
