### ISSUE TITLE
Number small can go larger than 100

### ISSUE THREAD

**Issue by AndreasArvidsson** [knausj85/knausj_talon#478]
If you say "ten five" number small will be 105.

**Comment by rntz** [comment]
I don't have enough time to fix this now, but I think there are probably two ways to address this issue:

1. Change the grammar of number_small so that "ten five" is not a valid small number.
2. Change the function number_small so that it interprets "ten five" as 15.

Any preference between these? I would personally be inclined to solution (1).

**Comment by rntz** [comment]
Okay, I've made a PR that takes approach #1.

**Comment by AndreasArvidsson** [comment]
I agree with #1
