### ISSUE TITLE
British Pound Sterling Symbol Request (£)

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#512]
We should add the British pound to knausj.

Some possible ideas for phrases to invoke it (note that 'pound' is already taken by the `#` symbol):

- ~pounds~ - removed at the suggestion of @rntz 
- GBP
- british pound (sign)
- pound sterling (sign)

**Comment by rntz** [comment]
We definitely shouldn't use "pounds" if we already use "pound"; commands which differ only by a single sound are a bad idea.

I think either "british pound" or "pound sterling" is reasonable. In fact, I'd mildly be in favor of removing "pound" for # entirely and using "pound sign" for £, since we already have "hash sign", "number sign", and "hash". But removing keys from the default configuration is a bit of a drastic step.
