### ISSUE TITLE
Ability to exit the homophone selection window without selection

### ISSUE THREAD

**Issue by xavier630** [knausj85/knausj_talon#530]
Currently if I trigger a homophones pop-up but don't pick an option (for example because my preferred option isn't there), the window sits there forever and I have to pick an option to make it go away.

![image](https://user-images.githubusercontent.com/9077250/127772437-cef87c0b-0d37-4b3e-926e-33688e4d5162.png)

A couple of ideas:
- A timeout so that the window disappears if no options are picked after some period of time, eg 30 seconds
- An exit button as seen on some of the other windows

I think an ideal solution would have both of these options implemented.

Talon v0.2.0-8

**Comment by fidgetingbits** [comment]
I have an hide button added in my repo already, but no timeout. I can open a pull request for it. 

I personally think that if we have the button then there's no point in having the timeout, unless we think adding timeouts for other windows eventually will make sense? If we had it it would have to be tied to a default off setting I guess for sure. Personally I'd find timeout for the windows a little bit confusing, especially because I just get distracted sometimes and then if it suddenly went away without my interaction, it might be unexpected.

I feel like similar to other dialogue windows, some additional command like `phones close` when the windows open make sense? I guess we have to assume that people don't always have a convenient way to click the hide button.

**Comment by xavier630** [comment]
1. There is a `phones hide` command currently.
2. +1 to adding your button.
3. I personally really like the timeout (with a really long timeout so the user didn't just get distracted, maybe 5 minutes) since it potentially saves an action.

**Comment by splondike** [comment]
I'm not sure having a timeout would be what I would expect; I don't know of too many UI elements that self hide after a timeout (aside from controls on video players).

@xavier630 Have you had a chance to use the 'phones hide' button/command over the last few days. How does that feel in terms of meeting your needs?

**Comment by xavier630** [comment]
Let's close, no need for the timeout 👍
