### ISSUE TITLE
Command history and other windows don't have a close button

### ISSUE THREAD

**Issue by michaelpog** [knausj85/knausj_talon#613]
The command history pop up menu and few others don't have a default close button.
I do understand that repeating the same command that opened the popup menu should close them.
However sometimes pop up windows show up by accident, from background noise for example, or while of watching a movie and forgetting to close Talon.
I think all popup windows should come with a default close button.

**Comment by splondike** [comment]
#588 Will address this.

**Comment by tararoys** [comment]
#588 partially addresses this.  It does not completely address this.  

Popup windows that #588 gives a close button include alphabet, symbols, formatters, modfier keys, special keys, and so on.  

It does not give a close button to 
- command history
- recent phrases
- homophones
- microphones

And I'm sure there's a couple of others that I'm missing. 

The difficulty is that, what do you do when there are two windows up at the same time, and both have a 'close' button?  As far as I know, Talon does not have a 'focus' on particular windows, and there isn't a visual indicator about which talon gui element has focus.  

Command history is one of the windows that you may want to have up while having the help menus open, so if you put a close button on it, then which of the two open windows are you supposed to close?

**Comment by splondike** [comment]
Ahh good point, yeah, agreed that it would be good for those to have a close button also.

If we stick a close button on all the windows then everything would be closable by the mouse. We also want to make it obvious how to close them by voice of course. The way I did this in the `talon_ui_helper` package was to just stick the voice command in as the label of the button. So instead of labelling the close button on command history "close" we'd instead label it "command history close" (and bind that as a new voice command).

How does that sound to y'all?

**Comment by splondike** [comment]
This is addressed by #699, closing this out.
