### ISSUE TITLE
Generic Talon files

### ISSUE THREAD

**Issue by wenkokke** [knausj85/knausj_talon#670]
I would like for knausj_talon to move towards the following organizational principle:

> A generic Talon file (e.g. [`operators.talon`][operators] or [`generic_editor.talon`][generic_editor]) should only define commands linked to unique abstract actions—one action per command—were the spoken command reflects the intention of the command (e.g. `go line start`) rather than the concrete key input (e.g. `press home`).

### Why not define command in terms of the abstract actions of other commands?
Let's look at [`clear all`][clear-all]. It is defined as `edit.select_all()` followed by `edit.delete()`. Spacemacs has a specific command for erasing the entire text buffer, `SPC b e y`. I shudder to imagine the circumstances that led to that command being considered necessary. Unfortunately, I cannot implement `clear all` as `SPC b e y`, since it is always implemented as `select all delete`.

Wherever or such not-quite-abstract commands exist in the current library, we should migrate them to abstract actions with default implementations. For example, we could declare `edit.clear_all()` with the current behavior as a default implementation.

### Why not add concrete actions to a generic Talon file?
Let's look at [`op pad colon`][op-pad-colon]. It's defined in the generic "operators" tag, which means that is available across many programming language modes. However, it is not linked to an abstract action, which means that you cannot override. Furthermore, its spoken command specifically references inserting a colon, but it does not refer to what the colon supposed to mean, so even if we could override it, what would it do? If it's Python's type annotation `s: str` then in Haskell we would like it to output ` :: `. If it's part of Java's for-each loop, then in Python we would like it to output ` in `.

I am opening this issue as a place to have a discussion about this.

[operators]: https://github.com/knausj85/knausj_talon/blob/60705a48008214e5ac2582f9740bef6b9cee762c/lang/tags/operators.talon
[generic_editor]: https://github.com/knausj85/knausj_talon/blob/429bbe30ee091f3f9bb4258a9d54af0edca0dec1/text/generic_editor.talon
[clear-all]: https://github.com/knausj85/knausj_talon/blob/429bbe30ee091f3f9bb4258a9d54af0edca0dec1/text/generic_editor.talon#L148
[op-pad-colon]: https://github.com/knausj85/knausj_talon/blob/182b28bb04494f55481003539536305e160295a3/lang/tags/operators.talon#L55

**Comment by rntz** [comment]
I am in agreement we should move in this direction, but I'm not convinced we should apply this too rigidly. In particular:

1. I worry about combinatorial action explosion. Creating a new action for every voice command could create a lot of actions. I think for `clear all` there's a clear benefit in combining them (overriding it in some contexts) but if there isn't a need and it would create a lot of boilerplate, it's ok to omit the abstract actions and we shouldn't waste effort trying to enforce this rule strictly.

2. It's okay to have actions like `op pad colon` which perform concrete rather than abstract things. Each have pros/cons and the choice is a matter of taste. For instance, I have a command `deckle` that inserts `: ` (colon followed by space). It's not intended to correspond to some semantic thing that depends upon what programming language I'm editing, it's literally just shorthand for `: `. Similarly, I have `do <user.symbol_key>+: " {user.join(symbol_key_list)} "` for inserting a sequence of symbols surrounded by spaces (`do equals` for ` = `, `do plus equals` for ` += `, `do plus plus` for ` ++ `, etc). The advantage of concrete actions is that they behave consistently in every context; I can use them for coding, writing text, writing tweets, etc. Sometimes a single concrete command (like `do <symbols>`) can fulfill the role of a bunch of language-specific commands. It's also useful to have commands that do more abstract/high-level things like "insert a type declaration" but not every command has to be that way.

I also have vague hopes to reorganize the generic_editor.talon commands in a more abstract way, by having some sort of verb-noun system that allows applying any verb (select, copy, cut, clear, go) to any noun (word left/right, line up/down, to bottom/top, ...), but so far I have no working prototype.

**Comment by wenkokke** [comment]
I think not applying it too rigidly is a good call.
