### ISSUE TITLE
'go <arrow keys>' conflicts with generic_editor 'go left/right/up/down'

### ISSUE THREAD

**Issue by auscompgeek** [knausj85/knausj_talon#713]
This is really only a problem if the edit actions are overridden, but one might want to do so for `vim`...

**Comment by rntz** [comment]
What behavior do you think you would like? I see three options:

1. Remove the generic_editor `go left/right/up/down` commands and only have `go <arrow keys>`. If you want custom commands for the edit actions, you can add them yourself.

2. Have `go <arrow keys>` use `edit.left()`/`edit.right()` etc instead of pressing the corresponding keys. Since the default implementations of these are to press the arrow keys, this should be *mostly* ok? However, it means there's no command to just press those arrow keys if `edit.left()` etc are overridden. Hm.

3. Have separate commands for pressing the arrow keys and issuing the edit actions. I'm not sure what these would be called, though.

**Comment by auscompgeek** [comment]
> Have separate commands for pressing the arrow keys and issuing the edit actions. I'm not sure what these would be called, though.

I've seen people (myself included) use the cardinal directions. Not sure if they should belong in knausj_talon, but something to consider.

In that scenario I think it would make sense to keep `go <arrow keys>` as is, to keep things simple.

**Comment by rntz** [comment]
Yeah, I'm inclined to leave `go <arrow keys>` as is and remove or comment out the go left/right/up/down commands in generic_editor.

**Comment by knausj85** [comment]
I would definitely keep `go <arrow keys>`

Could always use a synonym like walk/march/trek if there's value in keeping the generic_editor commands, but I'd be tempted to make that application-specific.

**Comment by pokey** [comment]
The approach we landed on during the grooming session today was to 

- have `go <user.arrow_keys>` map to `edit.direction` in generic editor (pressing the arrow keys as many times as was chained), 
- but then have a separate command `press <user.unmodified_key>` which can be used to directly press the specific key such as up or down 

wdyt @rntz ?

**Comment by rntz** [comment]
That seems ok, although it means `press` has three quite different meanings:

1. `press <user.keys>` to press a sequence of keys in *dictation* mode.
2. `press <user.modifiers>` to press a modifier key in command mode, eg. `press super`.
3. `press <user.unmodified_key>` to press an unmodified key in command mode, eg `press left`.

We already had (1) & (2), so this issue already existed, this just makes it more obvious. Maybe this merits a separate issue.

Anyway, if there are folks who want this, and knausj has signed off, I have no objection.

**Comment by rntz** [comment]
I made a PR to fix this and also my complaint about `press` being inconsistent: #742.
