### ISSUE TITLE
Operators and friends

### ISSUE THREAD

**Issue by PetrKryslUCSD** [knausj85/knausj_talon#791]
Operators are introduced in programming languages by saying `op something`.
What would be the disadvantages of just saying `something`? I can certainly see how
dictating code would be easier if I could just say `fox assign five` and `times 3`
to get `f = 5 * 3`.

**Comment by splondike** [comment]
We currently avoid new single word commands in this repo for a couple of reasons:

1. We believe they tend to be recognised less reliably.
2. They add more 'prefixes', increasing the chance of colliding with future commands.

For the second point, let's say we bound the 'assign' command to print out ' = '. This then 'uses up' the 'assign' prefix so it can't be used for any other commands active in the same context. As an example we might want to type some Python code into Github using 'force python' say. We might also want to have a command which would assign this issue to me. Due to the prefix collision we wouldn't be able to use 'assign' for the latter command.

You can definitely feel free to drop the prefix in your own repo if you prefer, but those are the reasons we don't tend to do it in knausj_talon.

**Comment by PetrKryslUCSD** [comment]
I concede that that is sound reasoning.
