### ISSUE TITLE
Make adding to additional_words.csv quicker

### ISSUE THREAD

**Issue by bra1nDump** [knausj85/knausj_talon#792]
My most common reason for opening user directory is adding to additional_words.csv. 

Should we:
* Option 1: add a command to add the selection additional_words
* Option 2: add a shortcut to open additional_words or other settings file

**Comment by phillco** [comment]
@wolfmanstout did (1) in his fork :)

**Comment by wolfmanstout** [comment]
Yeah, I made a fancy version that optionally lets you supply a spoken form, which it will test to ensure that the new vocabulary works (and if not, it adds the spoken form). It depends on some private APIs so it's not something I can push upstream yet, but I plan to factor it out into a separate repository at some point:
https://github.com/wolfmanstout/wolfmanstout_talon/blob/4cb0578bf3f2059f3f647d2ce7b41ac3da143243/code/vocabulary.py#L185

**Comment by rntz** [comment]
If we wanted to do (2), is there an action that opens a particular file in the user's preferred editor? Is there even a good way to do this cross-platform? We could definitely have the action even if not, so that users can override it to their preference, but it would be neat if we could just Do The Right Thing.

**Comment by nriley** [comment]
Addressed in #846 and #847.
