### ISSUE TITLE
window.y and window.height incorrect

### ISSUE THREAD

**Issue by ja-mesmugford** [knausj85/knausj_talon#90]
https://github.com/knausj85/knausj_talon/blob/dcbb1ea89fd1bfbd09f57c25d9dc8a8907270c42/code/mouse.py#L239

window.y and window.height don't seem to be correct. They seem to be 0 and 1070 respectively in every window on my 1200px tall monitor.

Hope this help

**Comment by knausj85** [comment]
@Ja-mesMugford 
See my response here.
https://github.com/talonvoice/beta/issues/58

since this currently finds the first window containing the coordinates, if you have a maximized window it could be using that at the moment? I don't know if Talon on Windows tracks the z-order of the windows. I

Note the dimensions of a maximized window will exclude any reserved space for e.g. start menu.

**Comment by lunixbochs** [comment]
talon on linux and mac is z ordered from top to bottom, it's not on windows yet. feel free to look up an api for figuring out Z order on windows and open an issue on talon/beta
