### ISSUE TITLE
We need a mechanism for deprecating actions

### ISSUE THREAD

**Issue by timo** [knausj85/knausj_talon#940]
I would like to deprecate the action `insert_with_history`, but there's not yet something for that.

We should probably log a warning and add "deprecated" to the description. There should probably also be a spot to put what the code should do instead to reduce friction for users.

**Comment by splondike** [comment]
Here's my idea. We have a two stage deprecation process for actions. First they display a popup notification about deprecation once per Talon session but otherwise still function. Second (4 months later say) they just display the notification and don't function. 6 months after that we can completely remove them.

In addition to the above we have a file that lists deprecated actions along with the date and some instructions about how to migrate off them. The deprecation notification would say "user.insert_with_history is deprecated please see DEPRECATED_ACTIONS.md" for the first case and "...is no longer supported..." for the second.

For the second non-functional deprecation we could move the action over to a 'deprecated_actions.py' file so it stopped cluttering up the original 'functional' file.

**Comment by gsingh93** [comment]
Another reason why having this deprecation code would be useful is that right now some commands are structured like verb-object while the recommendation is to structure them like object-verb. If we were to change all of these commands to match the recommendation, then that would lead to a lot of deprecated commands.

**Comment by splondike** [comment]
I've pushed up a proposal for the deprecation process and system in #1027 . It's a little simpler than the one I put in my above comment. The built in notification system in the PR is also only partial in that it doesn't handle the case of lists, or of people overriding captures or actions.

For all of these harder cases I think it would be ideal to have 1st party support. I.e. we get the ability to mark those things as deprecated somehow with a Talon API. We could also do something with abstract syntax tree processing, but that sounds a bit invasive.

If the PR looks good and gets merged, maybe we should close out this issue by just raising a feature request for 1st party deprecation of these constructs on the Talon issue tracker.

**Comment by splondike** [comment]
PR got merged in (see discussion on #1027 for what we eventually implemented). Closing out this issue.
